import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),...(process.env.TEST_PROXY?{proxy:{server:process.env.TEST_PROXY,bypass:'127.0.0.1,localhost'}}:{}),headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'https://yukiasunaaa.github.io/shijing-tang-poetry/',{waitUntil:'networkidle',timeout:60000});
await page.waitForSelector('.bar-row');
await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('.scene-art').count(),5);
assert.equal(new Set(await page.locator('.scene-art').evaluateAll(images=>images.map(image=>image.currentSrc))).size,5);
assert.equal(await page.title(),'诗境 · 全唐诗文本图谱');
assert.equal(await page.locator('.bar-row').count(),4);
assert.equal(await page.locator('#quote').textContent(),'春眠不觉晓，处处闻啼鸟。');
assert.ok(await page.locator('.scene-art').evaluateAll(images=>images.every(image=>image.complete&&image.naturalWidth>100)));
for(const id of ['plants','sky','colors','landscape','seasons']){
  await page.locator(`[data-category="${id}"]`).click();
}
await page.waitForTimeout(800);
assert.equal(await page.locator('.bar-row').count(),4);
await page.locator('.bar-row').last().click();
assert.equal(await page.locator('#selected-glyph').textContent(),'冬');
await page.setViewportSize({width:390,height:844});
await page.locator('[data-category="plants"]').click();await page.waitForTimeout(800);
assert.equal(await page.locator('.bar-row').count(),12);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.locator('[data-view="emotion"]').click();
await page.waitForSelector('.radar-shape');
await page.locator('#poet-search').fill('李白');
await page.locator('#poet-list button').first().click();
assert.equal(await page.locator('#emotion-poet').textContent(),'李白');
await page.locator('.radar-node').nth(1).click();
assert.match(await page.locator('#emotion-quote').textContent(),/李白/);
await page.locator('[data-view="cluster"]').click();
await page.waitForSelector('.poet-point');
assert.ok(await page.locator('.poet-point').count()>100);
assert.deepEqual(errors,[]);
console.log('Published HTTPS site verified: assets, fonts, real data, rapid category transitions, term selection, desktop/mobile layout.');
await browser.close();
